# ----------- CONFIGURABLE START -----------
title:            "Maleficush | Tech Blog"
description:      "Maleficush's Computer Tech Blog"
url:              https://maleficush.github.io # 域名
signoff:          "Maleficush" # Your name
facebook_appid:   #liveu
google_analytics: UA-101222464-1
share:            true
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         root
    url:          /
    external:     false
  - name:         Kubernetes
    url:          /kubernetes
    external:     false
  - name:         Prometheus
    url:          /prometheus
    external:     true
  - name:         archives
    url:          /archives
    external:     false
  - name:         tags
    url:          /tags
    external:     false
  - name:         about
    url:          /about
    external:     false
  - name:         test1
    url:          /test1
    external:     false
  - name:         test2
    url:          /test3
    external:     false
  - name:         test3
    url:          /test3
    external:     false
  - name:         test4
    url:          /test4
    external:     false
  - name:         test5
    url:          /test5
    external:     false
  - name:         test6
    url:          /test6
    external:     false
  - name:         test7
    url:          /test7
    external:     false
  - name:         test8
    url:          /test8
    external:     false
  - name:         test9
    url:          /test9
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
