# ----------- CONFIGURABLE START -----------
title:            "Maleficush | Tech Blog"
description:      "Maleficush's Computer Tech Blog"
url:              https://maleficush.github.io # 域名
signoff:          "Maleficush" # Your name
facebook_appid:   #liveu
google_analytics: UA-101222464-1
share:            true
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         All
    url:          /
    external:     false
  - name:         Devops
    url:          /devops
    external:     false
  - name:         DeepLearning
    url:          /deeplearning
    external:     false
  - name:         Backend
    url:          /backend
    external:     false
  - name:         Frontend
    url:          /frontend
    external:     false
  - name:         archives
    url:          /archives
    external:     false
  - name:         tags
    url:          /tags
    external:     false
  - name:         about
    url:          /about
    external:     false


# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
